modLoader = "javafml"
loaderVersion = "[47,)"
license = "GPL-3.0"
issueTrackerURL="https://github.com/Neferge466/Element-Endow/issues"
[[mods]]
modId = "element_endow"
version = "0.0.1"
displayName = "Element Endow"
displayURL="https://github.com/Neferge466/Element-Endow"
authors = "NEFOR"
displayTest="MATCH_VERSION"
description = '''A Minecraft mod that adds elemental attributes to entities and implements an elemental reaction system.
Players can harness the power of fire, water, earth, air, lightning, ice, nature, and metal elements.
The mod features both internal elemental synergies and induced combat reactions with customizable effects.'''
[[dependencies.element_endow]]
modId = "forge"
mandatory = true
versionRange = "[47.3.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.element_endow]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"